return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "intelephense",
      "clangd",
      "sqls",
      "clang-format",
      -- "lemminx",
      "html-lsp",
      "nextls",
      "stimulus-language-server",
      "css-lsp",
      "htmx-lsp",
      "tailwindcss-language-server",
      "marksman",
      "typescript-language-server",
      "gopls",
      "pretty-php",
      "prettier",
      "black",
      "lua-language-server",
      "mypy",
      "pyright",
      "ruff",
      "rust-analyzer",
      "stylua",
      "volar",
    },
  },
}
